call addSharedMetadataHeaders even when token has not expired
googleapis/google-auth-library-nodejs pull request #1116
Opened 2021-01-17 00:09 UTC by hideto0710

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-auth-library-nodejs/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1114  🦕

---

```
npm test -- -g "getRequestHeaders should populate x-goog-user-project"
```
before
```
  refresh
    ✓ getRequestHeaders should populate x-goog-user-project header if quota_project_id present
    1) getRequestHeaders should populate x-goog-user-project header if quota_project_id present and token has not expired

  1 passing (43ms)
  1 failing

  1) refresh
       getRequestHeaders should populate x-goog-user-project header if quota_project_id present and token has not expired:
     AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ undefined
- 'my-quota-project'

```
after
```
  refresh
    ✓ getRequestHeaders should populate x-goog-user-project header if quota_project_id present
    ✓ getRequestHeaders should populate x-goog-user-project header if quota_project_id present and token has not expired
```

2021-01-17 00:13 UTC, hideto0710 commented
@googlebot I signed it!

2021-01-21 21:27 UTC, bcoe commented
@hideto0710 good catch 👍 (CC: @sofisl). If I'm following correctly, the quota project was properly populated up until the token refreshed?

2021-01-21 21:31 UTC, bcoe requested changes
mind adding the additional test? thank you very much for the contribution 🎉

2021-01-21 21:31 UTC, bcoe commented on test/test.refresh.ts
> +  it('getRequestHeaders should populate x-goog-user-project header if quota_project_id present and token has not expired', async () => {
I think we should also add a test that makes sure you get the appropriate header populated after the expiry?

(_sorry for the slow review, we'll work on getting this out the door quickly._).

2021-01-26 01:44 UTC, bcoe approved these changes

2021-01-27 00:58 UTC, merged

2021-01-27 00:59 UTC, bcoe commented
@hideto0710 thank you very much for the contribution 👍