fix: Validate token_url and service_account_impersonation_url
googleapis/google-auth-library-nodejs pull request #1229
Opened 2021-08-07 03:57 UTC by xil222

Add token_url and service_account_impersonation_url validation in BaseExternalClient
https://buganizer.corp.google.com/issues/193694061

2021-08-09 08:00 UTC, bojeil-google requested changes

2021-08-10 20:13 UTC, xil222 commented on src/auth/baseexternalclient.ts
> +    }
ok, since token_url is required field in constructor input, an error will be thrown if it is missing. Therefore, I can just remove the check here.

2021-08-10 22:28 UTC, bcoe requested changes

2021-08-10 22:28 UTC, bcoe commented on src/auth/baseexternalclient.ts
> +    matchUrlPatterns.push(
wondering if this could just be defined as a `const` at the top of the file, rather than us using `push` to populate an array/

2021-08-12 09:00 UTC, bojeil-google requested changes

2021-08-12 19:16 UTC, xil222 commented on test/test.baseexternalclient.ts
> +        throw new Error(
Test would fail telling which url is invalid in that way, 
I want to throw informative error message telling which url is wrong.

2021-08-12 20:03 UTC, xil222 commented on test/test.baseexternalclient.ts
> +        throw new Error(
I think without a try/catch, the failing statement only would be:
AssertionError [ERR_ASSERTION]: Missing expected exception (Error).
without telling which url is wrong.
I want it throw a more informative error message. I think I can remove try/catch in those 2 valid tests

2021-08-13 06:17 UTC, bojeil-google commented on src/auth/baseexternalclient.ts
> +/** */
`/** The variable portion pattern in a Google APIs domain. */`

2021-08-13 06:17 UTC, bojeil-google commented on src/auth/baseexternalclient.ts
> +const STAR_PATTERN = '[^\\.\\s\\/\\\\]';
You can include the `+` too, since it is also include in all the patterns:
`[^\\.\\s\\/\\\\]+`

2021-08-13 06:17 UTC, bojeil-google commented on test/test.baseexternalclient.ts
> +        throw new Error(
Then I suggest you move the array outside the test and add the test case in the description. This is a more common way of doing that and catching the failing case:
```
invalidTokenUrls.forEach((invalidUrl) => {
  it(`should throw on invalid token url: ${invalidUrl}`, () => {
    ...
  });
});
```

2021-08-16 21:13 UTC, bojeil-google approved these changes
Changes look good from my end. Thanks for putting this together.

2021-08-17 19:40 UTC, bcoe commented on test/test.baseexternalclient.ts
> +        'https://iamcredentials.us-west-1.googleapis.com',
solid tests 👍

2021-08-17 19:40 UTC, bcoe approved these changes

2021-08-17 19:42 UTC, merged