feat: add api key support
googleapis/google-auth-library-nodejs pull request #1491
Opened 2022-11-18 23:59 UTC by arithmetic1728

Add api key support. The feature has been tested with the following sample: 

https://github.com/arithmetic1728/nodejs-api-key-sample/blob/main/index.js

```
async function main() { 
    const language = require('@google-cloud/language'); 

    const client = new language.LanguageServiceClient({'apiKey': '<FILL IN THE API KEY>'});
    
    const text = 'Hello, World'; 
    const document = { type: 'PLAIN_TEXT', content: text, }; 
    const analyzeSentimentRequest = { document: document, encodingType: 'UTF8', };
    try { 
        const [response] = await client.analyzeSentiment(analyzeSentimentRequest); 
        const sentiment = response.documentSentiment; 
        console.log(`Text: ${text}`); 
        console.log(`Sentiment score: ${sentiment.score}`); 
        console.log(`Sentiment magnitude: ${sentiment.magnitude}`); 
    } catch (err) { 
        console.log(err) 
    } 
} 

main()
```

2022-11-19 04:27 UTC, arithmetic1728 commented
The docs failure doesn't seem to be related to my changes.

2022-11-22 20:00 UTC, bcoe requested changes
At a glance, things look good to me, but the sample doesn't follow guidelines. Specifically, there's not region tag, which would mean it can't be embedded on cloud.google.com.

I would use this as an example:

https://github.com/googleapis/google-auth-library-nodejs/blob/main/samples/authenticateImplicitWithAdc.js

2022-11-22 20:00 UTC, bcoe commented on samples/api-key.js
> +/**
This does not follow sample guidelines, so could not be embedded on cloud.google.com:

https://googlecloudplatform.github.io/samples-style-guide/#region-tags

2023-06-30 17:21 UTC, danielbankhead reviewed
Looks good - however I'm not seeing any other langs using this region tag. Do you need assistance in this area?

2023-07-02 04:12 UTC, arithmetic1728 commented
we decided not to implement api key support as there is a workaround for the users, closing the PR.

2023-07-02 04:12 UTC, closed without merging