feat: Extend API Key Support
googleapis/google-auth-library-nodejs pull request #1835
Opened 2024-07-11 22:14 UTC by danielbankhead

🦕

2024-07-17 20:01 UTC, sofisl requested changes

2024-07-17 20:01 UTC, sofisl commented on src/auth/googleauth.ts
> +    if ('apiKey' in options && options.apiKey) {
I actually think API Key should override ADC:

```Additionally, if application default credentials (ADC) are enabled and an API key is specified, ADC should be ignored.```

Also, we should add an error situation if an API Key and credentials are used together:

```API Keys and Credentials are mutually exclusive authentication methods and cannot be used together.```

2024-07-17 20:02 UTC, sofisl commented
Thank you for taking on this work!!

2024-08-02 22:19 UTC, danielbankhead commented on .readme-partials.yaml
> +
Added

2024-08-16 22:31 UTC, danielbankhead commented on samples/authenticateAPIKey.js
> +// Copyright 2024 Google LLC
Designed to match:
- https://cloud.google.com/docs/authentication/api-keys#using-with-client-libs

2024-08-19 16:57 UTC, sofisl commented on README.md
> +Note, classes that extend from this can utilize this parameter as well, such as `JWT` and `UserRefreshClient`.
```suggestion
Note, classes that extend from `OAuth2Client` can utilize this parameter as well, such as `JWT` and `UserRefreshClient`.
```

2024-08-19 17:03 UTC, sofisl approved these changes

2024-08-19 20:14 UTC, merged